### ISSUE TITLE
Bug - DME backup not lit by dome lt

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#42]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start at night
2. Turn on DOME LT
3. Observer backup DME instrument

**Expected behaviour**
Instrument is lit by DOME LT

**Comment by legoboyvdlp** [comment]
reproduced, thanks, looks like only the needles get lit?

**Comment by merspieler** [comment]
affirmative

**Comment by vezza** [comment]
I've just pushed a bug fix... the lighting of the ddrmi instrument is controlled by the "INTEG LT - MAIN PNL & PED" knob on the pedestal panel.
Anyway it seems to me that DME indicators aren't working... can someone check?

**Comment by legoboyvdlp** [comment]
It still doesn't work...?

![image](https://user-images.githubusercontent.com/10434911/77192556-a873e500-6ad4-11ea-9591-17c859423796.png)

![image](https://user-images.githubusercontent.com/10434911/77192603-b6296a80-6ad4-11ea-8f4d-97b005940a89.png)

Does look good with the panel light on though.

The clock still needs lit too, both with panel flood and dome.

**Comment by merspieler** [comment]
Yes... doesn't seem to work in your 1st pic

**Comment by vezza** [comment]
I mean that DME-1 and DME-2 display's do not show any information...

**Comment by merspieler** [comment]
Afaik they are not yet implemented.

@vezza As well for you. please pull with `git pull --rebase` to avoid unnecessary merge commits.

**Comment by vezza** [comment]
Ok thanks... As for the lighting I've now realized what you both mean... I'm having a look at it now

**Comment by legoboyvdlp** [comment]
I'll implement the DME shortly. Thanks for fixing!
